profile: chatanoo-admin
region: eu-west-1
iam:
  role:
      name: arn:aws:iam::175828319502:role/lambda_basic_execution

lambda:
  name: GAReporter
  description: Chatanoo GAReporter
  handler: handler.handler
  runtime: nodejs
  memory_size: 128
  timeout: 3
  event_sources:
    -
      arn: arn:aws:sns:eu-west-1:175828319502:chatanoo-events

env: 
  - GA_AU_ID=UA-44078448-1