profile: mathieu.desve
region: eu-west-1
iam:
  role:
      name: arn:aws:iam::175828319502:role/aws-lambda-dynamo-role

lambda:
  name: ExportToDynamo
  description: Export Chatanoo Items to DynamoDB
  handler: export_to_dynamo/index.handler
  runtime: nodejs
  memory_size: 128
  timeout: 3
  event_sources:
    -
      arn: arn:aws:s3:::chatanoo-medias-input

env:
  - MYSQL_RDS_HOST=chatanoo.cej9ktkapfol.eu-west-1.rds.amazonaws.com
  - MYSQL_RDS_PORT=3306
  - MYSQL_RDS_DB=chatanoo
  - MYSQL_RDS_USER=chatanoo
  - MYSQL_RDS_PASS=rfwGwU5Alb8RcB

  - DYNAMO_DB=chatanoo-items
