---
profile: chatanoo-admin
region: eu-west-1
iam:
  role:
      name: lambda_basic_execution
      policy: oneClick_lambda_basic_execution_1431782640785
lambda:
  name: Mailer
  zipfile_name: Mailer.zip
  description: Chatanoo Mailer
  path: src/
  handler: handler.handler
  runtime: nodejs
  memory_size: 128
  timeout: 3
  event_sources:
    -
      # change this to refer to your own SNS topic
      arn: arn:aws:sns:eu-west-1:175828319502:chatanoo-events-staging
  test_data: input.json