---
profile: chatanoo-admin
region: eu-west-1
iam:
  policy:
      name: AmazonElasticTranscoderJobsSubmitter
  role:
      name: lambda_s3_exec_role
      policy: oneClick_lambda_s3_exec_role_1431762514075
lambda:
  name: MediasTranscoderStaging
  zipfile_name: MediasTranscoder.zip
  description: Chatanoo MediasTranscoder Staging
  path: src/
  handler: handler.handler
  runtime: nodejs
  memory_size: 128
  timeout: 3
  event_sources:
    -
      arn: arn:aws:s3:::chatanoo-medias-input-staging
  test_data: input.json